@echo off

SET PROJECT_FOLDER=Keil
SET KEIL_PROJECT_NAME_UVPROJX=Template.uvprojx

SET PRODUCTION_FOLDER=Production
SET TMP_FOLDER=ci_tmp
SET BUILD_LOG=build.log

IF "%PROJECT_TARGET%"=="Template" (
	SET KEIL_PROJECT_OUTPUT_DIR=.\obj\
	SET KEIL_PROJECT_LISTING_DIR=.\lst\
	SET KEIL_PROJECT_OPTIM_LEVEL=3
)
SET PROJECT_TARGET_LIST[0]=Template
SET KEIL_PROJECT_OUTPUT_DIR_LIST[0]=.\obj\
SET KEIL_PROJECT_LISTING_DIR_LIST[0]=.\lst\
SET KEIL_PROJECT_OPTIM_LEVEL_LIST[0]=3

SET PROJECT_TARGET_LIST_LENGTH=0
